* Overcoming Procrastination [[http://counselingcenter.illinois.edu/brochures/overcoming-procrastination][web]]
** Definition
- avoidance of a specific task or work which needs to be accomplished
  - reminds us of past experiences where we have felt *guilty, lazy, inadequate, anxious, or stupid*
  - implies a *value judgment*; if you procrastinate, you are bad, and as such, you lack worth as a person.
** Causes
- carefully analyze those situations where your work is not being completed
  - the cause is poor time management?
    - if so, you will need to learn and develop time management skills
    - if you know how to manage your time but don’t make use of those skills, you may have a more serious problem.
      - *Lack of Relevance* – If something is neither relevant nor meaningful to you personally, it may be difficult to get motivated even to begin.
      - *Acceptance of Another’s Goals* – If a project has been imposed or assigned to you and it is not consistent with your own interests, you may be reluctant to spend the necessary time to see it to conclusion.
      - *Perfectionism* - Having unreachable standards will discourage you from pursuing a task. Remember, perfection is unattainable.
      - *Evaluation Anxiety* – Since others’ responses to your work are not under your direct control, overvaluing these responses can create the kind of anxiety that will interfere with work getting accomplished.
      - *Ambiguity* - If you are uncertain of what is expected of you, it may be difficult to get started.
      - *Fear of the Unknown* - If you are venturing into a new realm or field, you don’t have any way of knowing how well you’ll do. Such an uncertain outcome may inhibit your desire to begin.
      - *Inability to Handle the Task* – If through lack of training, skill, or ability you feel that you lack the personal resources to do the job, you may avoid it completely.
** Many forms
- Once you surmounted the emotional block by
  - acknowledging your procrastination (guilt, anxiety, feelings of inadequacy)
  - analyzing the underlying causes
- clearly specify *how you procrastinate*. Do you
  - act as though if you *ignore* a task, it will go away?
  - *underestimate* the work involved in the task, or overestimate your abilities and resources in relationship to the task?
  - deceive yourself into believing that a mediocre performance or *lesser standards are acceptable* (thus avoiding working harder leading to choices of important life goals)?
  - deceive yourself by *substituting one worthy activity for another*? (e.g. room cleaning instead of writing)
  - believe that *repeated minor delays are harmless*? (e.g. 5min TV instead of writing)
  - *dramatize a commitment* to a task rather than actually doing it? (e.g. books on vacation but never opening them, or declining invitations for pleasurable events, but still not pursuing the work at hand, staying in a constant state of unproductive readiness to work)
  - persevere on *only one portion* of the task? (e.g. only introductory paragraph)
  - become *paralyzed in deciding* between alternative choices? (e.g. choosing topic instead of writing)
** What to do
- visualize yourself in one or more of the above situations
- write down from the above examples those principles which apply to you
- make honest decisions about your work
  - if you wish to spend only a minimal amount of effort or time on a particular task, admit it
  - do not allow guilt feelings to interfere
  - weigh the consequences of various amounts of investment in a project
  - find the optimal return for your investment.
  - admit to yourself that you do want to achieve certain goals and accept the responsibilities involved in meeting those goals.
- acquire an adequate understanding of what is necessary to accomplish a task within a given time frame.
- distinguish between activities which dramatize your sense of commitment and those which will help you accomplish the task.
  - devote only that amount of time which is appropriate for each part of a task.
  - develop an overview of the entire project and visualize the steps that are needed to reach completion.
** Effective planning
- *segment the task* into small (more manageable) steps.
- *distribute the small steps reasonably within the given time frame*.
- *intersperse rewards, relaxation, and gratification for work completed*
- *monitor your progress* on the small steps.
  - watch for the pitfalls discussed earlier.
  - assess problems when they arise and do something about them quickly.
  - keep track of the segments and how they fit together to form the whole picture.
  - reassess time commitments as necessary.
- be *reasonable in your expectations of yourself*.
  - perfectionistic or extremely strict expectations may cause you to rebel or may sabotage your progress.
