* [[http://time.com/3210420/5-fool-proof-ways-to-end-procrastination-today/][5 Fool-Proof Ways to End Procrastination Today]]
** Pay attention to these inner-dialogue sentences (and causes of procrastination)
1. It's easy to do so I'll fit it in later (Complacency)
   - strong self-confidence
   - laziness
   - lack of concern
2. I'd much rather do something easier instead (Avoiding discomfort)
   - unpleasantness of an activity
   - pleasantness of another activity
3. I won't do it because I'll probably fail (Fear of failure)
4. I'm just not in the mood to do this right now (Emotional state)
   - too tired
   - too hungry
   - too stressed
5. I've done everything I could, and still no progress has been made (Action illusion)
** Tactics for remedy
*** Strive for 5
Pick up a project you've been putting off, and
give it just 300 seconds of your time. Then,
stop and reassess. After awhile,
the momentum of beginning the task will carry you forward.
*** Home run
Set (realistic) goals and (suitable) rewards. Each time you hit a goal, you earn the reward.
Select a time to review your progress and adjust your targets accordingly.
*** Be good to yourself
Imagine a conversation between 'you today' and 'you tomorrow'... what would he have to say?
*** Set creative punishments
Make the consequences of inaction so unbearable that you have no choice but to get busy now.
You could write a check to someone or something you really dislike.
Give the check to a friend with strict instructions to mail the check if you do not achieve your goal.
*** I was there
Going public with a goal increases your support and accountability.
Ask for support, but don't kid yourself that support equals progress.
